### ISSUE TITLE
cannot import name 'url' from 'django.conf.urls'

### ISSUE THREAD

**Issue by kntiwary** [RealmTeam/django-rest-framework-social-oauth2#259]
django.conf.urls.url() was deprecated in Django 3.0, and is removed in Django 4.0+

**Comment by satvik6005** [comment]
so does that mean that django-rest-framework-social-oauth2 does not work with django4.0+

**Comment by brandondunc94** [comment]
Not sure why it hasn't been merged yet, but you can add this to your requirements.txt 

django-rest-framework-social-oauth2 @ git+https://github.com/islam-kamel/django-rest-framework-social-oauth2

**Comment by SukiCZ** [comment]
@islam-kamel Could you release a new version please?

**Comment by SukiCZ** [comment]
@kntiwary I've just released new version with [this fix](https://github.com/RealmTeam/django-rest-framework-social-oauth2/blob/1.2.0/rest_framework_social_oauth2/urls.py#L2).

**Comment by islam-kamel** [comment]
> @kntiwary I've just released new version with [this fix](https://github.com/RealmTeam/django-rest-framework-social-oauth2/blob/1.2.0/rest_framework_social_oauth2/urls.py#L2).

Thanks
